name: GCP Polaris Onboarding

on:
  push:
    branches:
      - 
    paths:
      - gcp_projects/**
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform_code
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./gcp_projects

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Upload Terraform State (Optional)
        uses: actions/upload-artifact@v3
        with:
          name: tf-state
          path: ./gcp_projects/terraform.tfstate
